import tweepy
from loguru import logger
from pathlib import Path
from config import settings
from database import db
from semantic_memory import semantic_memory

class TwitterPublisher:
    def __init__(self):
        self.dry_run = settings.twitter_dry_run
        self.client = None
        self.api_v1 = None

        if not self.dry_run:
            if not all([settings.twitter_api_key, settings.twitter_api_secret,
                       settings.twitter_access_token, settings.twitter_access_token_secret]):
                logger.error("Twitter credentials missing. Forcing DRY RUN mode.")
                self.dry_run = True
            else:
                try:
                    # Client v2 for tweeting
                    self.client = tweepy.Client(
                        consumer_key=settings.twitter_api_key,
                        consumer_secret=settings.twitter_api_secret,
                        access_token=settings.twitter_access_token,
                        access_token_secret=settings.twitter_access_token_secret
                    )
                    
                    # API v1.1 for media upload
                    auth = tweepy.OAuth1UserHandler(
                        settings.twitter_api_key,
                        settings.twitter_api_secret,
                        settings.twitter_access_token,
                        settings.twitter_access_token_secret
                    )
                    self.api_v1 = tweepy.API(auth)
                    
                    logger.success("Twitter Client (v2 + v1.1) initialized.")
                except Exception as e:
                    logger.error(f"Failed to initialize Twitter client: {e}")
                    self.dry_run = True

    def publish(self, draft_id: int, text: str, media_path: str = None) -> bool:
        """
        Публікує текст в Twitter. Повертає True, якщо успішно.
        При помилці кидає виняток — retry-логіку обробляє RetryManager.
        """
        full_media_path = None
        if media_path:
            full_media_path = Path(settings.db_path).parent / media_path

        if self.dry_run:
            logger.info(f"[DRY RUN] Would publish tweet for Draft ID {draft_id}:")
            logger.info(f"[DRY RUN] Tweet text:\n{text}")
            if full_media_path and full_media_path.exists():
                logger.info(f"[DRY RUN] Attached Media: {full_media_path}")
            db.record_publish_success(draft_id, f"mock_tweet_{draft_id}")
            logger.info(f"[DRY RUN] Skipping semantic_memory.save() in Dry Run mode.")
            return True

        if not self.client or not self.api_v1:
            # Кидаємо виняток замість тихого False — RetryManager
            # класифікує це як permanent і переведе в failed
            raise RuntimeError("401 unauthorized: Twitter client is not available")

        logger.info(f"Publishing Draft ID {draft_id} to Twitter...")
        
        media_ids = None
        if full_media_path and full_media_path.exists():
            try:
                logger.info(f"Uploading media: {full_media_path.name}")
                media = self.api_v1.media_upload(filename=str(full_media_path))
                media_ids = [media.media_id]
            except Exception as e:
                logger.error(f"Failed to upload media: {e}")
                raise RuntimeError(f"Media upload failed: {e}")

        response = self.client.create_tweet(text=text, media_ids=media_ids)
        tweet_id = response.data['id']
        logger.success(f"Tweet published successfully! ID: {tweet_id}")

        db.record_publish_success(draft_id, str(tweet_id))
        
        # Semantic memory update ONLY after confirmed real publish and local DB transaction
        try:
            semantic_memory.save(text)
        except Exception as e:
            logger.warning(f"Failed to update semantic memory for draft {draft_id}: {e}")
            
        return True

publisher = TwitterPublisher()

if __name__ == "__main__":
    logger.info("Testing Twitter Publisher...")
    test_draft_id = 999
    publisher.publish(test_draft_id, "This is a test tweet generated by AI Bot V1. #AI #Testing")
